// Code generated by ent, DO NOT EDIT.

package userchannel

const (
	// Label holds the string label denoting the userchannel type in the database.
	Label = "user_channel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldRoleType holds the string denoting the role_type field in the database.
	FieldRoleType = "role_type"
	// Table holds the table name of the userchannel in the database.
	Table = "user_channels"
)

// Columns holds all SQL columns for userchannel fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldChannelID,
	FieldRoleType,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
