// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"slack-application/ent/message"
	"slack-application/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetData sets the "data" field.
func (mu *MessageUpdate) SetData(s string) *MessageUpdate {
	mu.mutation.SetData(s)
	return mu
}

// SetAttachment sets the "attachment" field.
func (mu *MessageUpdate) SetAttachment(s string) *MessageUpdate {
	mu.mutation.SetAttachment(s)
	return mu
}

// SetUserID sets the "user_id" field.
func (mu *MessageUpdate) SetUserID(i int64) *MessageUpdate {
	mu.mutation.ResetUserID()
	mu.mutation.SetUserID(i)
	return mu
}

// AddUserID adds i to the "user_id" field.
func (mu *MessageUpdate) AddUserID(i int64) *MessageUpdate {
	mu.mutation.AddUserID(i)
	return mu
}

// SetWorkspaceID sets the "workspace_id" field.
func (mu *MessageUpdate) SetWorkspaceID(i int64) *MessageUpdate {
	mu.mutation.ResetWorkspaceID()
	mu.mutation.SetWorkspaceID(i)
	return mu
}

// AddWorkspaceID adds i to the "workspace_id" field.
func (mu *MessageUpdate) AddWorkspaceID(i int64) *MessageUpdate {
	mu.mutation.AddWorkspaceID(i)
	return mu
}

// SetCreatedAt sets the "created_at" field.
func (mu *MessageUpdate) SetCreatedAt(t time.Time) *MessageUpdate {
	mu.mutation.SetCreatedAt(t)
	return mu
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, MessageMutation](ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Data(); ok {
		_spec.SetField(message.FieldData, field.TypeString, value)
	}
	if value, ok := mu.mutation.Attachment(); ok {
		_spec.SetField(message.FieldAttachment, field.TypeString, value)
	}
	if value, ok := mu.mutation.UserID(); ok {
		_spec.SetField(message.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.AddedUserID(); ok {
		_spec.AddField(message.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.WorkspaceID(); ok {
		_spec.SetField(message.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.AddedWorkspaceID(); ok {
		_spec.AddField(message.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetData sets the "data" field.
func (muo *MessageUpdateOne) SetData(s string) *MessageUpdateOne {
	muo.mutation.SetData(s)
	return muo
}

// SetAttachment sets the "attachment" field.
func (muo *MessageUpdateOne) SetAttachment(s string) *MessageUpdateOne {
	muo.mutation.SetAttachment(s)
	return muo
}

// SetUserID sets the "user_id" field.
func (muo *MessageUpdateOne) SetUserID(i int64) *MessageUpdateOne {
	muo.mutation.ResetUserID()
	muo.mutation.SetUserID(i)
	return muo
}

// AddUserID adds i to the "user_id" field.
func (muo *MessageUpdateOne) AddUserID(i int64) *MessageUpdateOne {
	muo.mutation.AddUserID(i)
	return muo
}

// SetWorkspaceID sets the "workspace_id" field.
func (muo *MessageUpdateOne) SetWorkspaceID(i int64) *MessageUpdateOne {
	muo.mutation.ResetWorkspaceID()
	muo.mutation.SetWorkspaceID(i)
	return muo
}

// AddWorkspaceID adds i to the "workspace_id" field.
func (muo *MessageUpdateOne) AddWorkspaceID(i int64) *MessageUpdateOne {
	muo.mutation.AddWorkspaceID(i)
	return muo
}

// SetCreatedAt sets the "created_at" field.
func (muo *MessageUpdateOne) SetCreatedAt(t time.Time) *MessageUpdateOne {
	muo.mutation.SetCreatedAt(t)
	return muo
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (muo *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks[*Message, MessageMutation](ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.Data(); ok {
		_spec.SetField(message.FieldData, field.TypeString, value)
	}
	if value, ok := muo.mutation.Attachment(); ok {
		_spec.SetField(message.FieldAttachment, field.TypeString, value)
	}
	if value, ok := muo.mutation.UserID(); ok {
		_spec.SetField(message.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.AddedUserID(); ok {
		_spec.AddField(message.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.WorkspaceID(); ok {
		_spec.SetField(message.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.AddedWorkspaceID(); ok {
		_spec.AddField(message.FieldWorkspaceID, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
