// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"slack-application/ent/predicate"
	"slack-application/ent/userworkspace"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserWorkspaceDelete is the builder for deleting a UserWorkspace entity.
type UserWorkspaceDelete struct {
	config
	hooks    []Hook
	mutation *UserWorkspaceMutation
}

// Where appends a list predicates to the UserWorkspaceDelete builder.
func (uwd *UserWorkspaceDelete) Where(ps ...predicate.UserWorkspace) *UserWorkspaceDelete {
	uwd.mutation.Where(ps...)
	return uwd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uwd *UserWorkspaceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, UserWorkspaceMutation](ctx, uwd.sqlExec, uwd.mutation, uwd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uwd *UserWorkspaceDelete) ExecX(ctx context.Context) int {
	n, err := uwd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uwd *UserWorkspaceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userworkspace.Table, sqlgraph.NewFieldSpec(userworkspace.FieldID, field.TypeInt))
	if ps := uwd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uwd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uwd.mutation.done = true
	return affected, err
}

// UserWorkspaceDeleteOne is the builder for deleting a single UserWorkspace entity.
type UserWorkspaceDeleteOne struct {
	uwd *UserWorkspaceDelete
}

// Where appends a list predicates to the UserWorkspaceDelete builder.
func (uwdo *UserWorkspaceDeleteOne) Where(ps ...predicate.UserWorkspace) *UserWorkspaceDeleteOne {
	uwdo.uwd.mutation.Where(ps...)
	return uwdo
}

// Exec executes the deletion query.
func (uwdo *UserWorkspaceDeleteOne) Exec(ctx context.Context) error {
	n, err := uwdo.uwd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userworkspace.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uwdo *UserWorkspaceDeleteOne) ExecX(ctx context.Context) {
	if err := uwdo.Exec(ctx); err != nil {
		panic(err)
	}
}
