// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// ChannelMessage is the predicate function for channelmessage builders.
type ChannelMessage func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// UserChannel is the predicate function for userchannel builders.
type UserChannel func(*sql.Selector)

// UserWorkspace is the predicate function for userworkspace builders.
type UserWorkspace func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)

// Workspace is the predicate function for workspace builders.
type Workspace func(*sql.Selector)
